#!/bin/bash

# Create 20 text files
for i in {1..20}; do
    echo "This is file $i" > "file_$i.txt"
done

# Rename the first 5 files to .yml extension
for i in {1..5}; do
    mv "file_$i.txt" "file_$i.yml"
done

# Print the latest created top 5 files
echo "Latest created top 5 files:"
ls -lt | head -n 5
